canton {
  participants {
    citi {
      storage.type = memory
      ledger-api.port = 5011
      admin-api.port = 5012
      http-ledger-api.port = 5013
    }
    morganstanley {
      storage.type = memory
      ledger-api.port = 5021
      admin-api.port = 5022
      http-ledger-api.port = 5023
    }
  }

  sequencers {
    dtccSequencer {
      storage.type = memory
      public-api.port = 5001
      admin-api.port = 5002
    }
  }

  mediators {
    dtccMediator {
      storage.type = memory
      admin-api.port = 5003
    }
  }
}
