canton {
  participants {
    bank {
      storage.type = memory
      ledger-api.port = 5011
      admin-api.port = 5012
      http-ledger-api.port = 5013
    }
    issuer {
      storage.type = memory
      ledger-api.port = 5031
      admin-api.port = 5032
      http-ledger-api.port = 5033
    }
  }

  sequencers {
    publicSequencer {
      storage.type = memory
      public-api.port = 5001
      admin-api.port = 5002
    }
    consortiumSequencer {
      storage.type = memory
      public-api.port = 5004
      admin-api.port = 5005
    }
  }

  mediators {
    publicMediator {
      storage.type = memory
      admin-api.port = 5003
    }
    consortiumMediator {
      storage.type = memory
      admin-api.port = 5006
    }
  }
}
