canton {
  participants {
    citi {
      storage.type = memory
      ledger-api.port = 5011
      admin-api.port = 5012
      http-ledger-api.port = 5013
    }
    goldmansachs {
      storage.type = memory
      ledger-api.port = 5031
      admin-api.port = 5032
      http-ledger-api.port = 5033
    }
  }

  sequencers {
    dtccSequencer {
      storage.type = memory
      public-api.port = 5001
      admin-api.port = 5002
    }
    euroclearSequencer {
      storage.type = memory
      public-api.port = 5004
      admin-api.port = 5005
    }
  }

  mediators {
    dtccMediator {
      storage.type = memory
      admin-api.port = 5003
    }
    euroclearMediator {
      storage.type = memory
      admin-api.port = 5006
    }
  }
}
